[phases.setup]
nixPkgs = ["nodejs_20", "python311Full"]

[phases.install]
cmds = [
  "npm install --include=dev",
  "python3 -m pip install -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
  "npm run build --workspace=frontend",
  "npm run build --workspace=backend"
]

[start]
cmd = "bash start.sh"
